kernel-mods += kernel.o

kernel-src = kernel/console.c \
	kernel/kprintf.c \
	kernel/mem/mem.c \
	kernel/mem/gheap.c \
	kernel/mem/buddy.c \
	kernel/threads/threads.c \
	kernel/threads/queue.c \
	kernel/threads/sched.c \
	kernel/threads/wait.c
