CFLAGS += -mno-sse -mno-avx -mno-mmx -mno-red-zone

kernel-mods += x86_64.o

x86_64-src = arch/x86_64/cores.c \
	arch/x86_64/init.c \
	arch/x86_64/interrupts.c \
	arch/x86_64/paging.c \
	arch/x86_64/zones.c

